# Continuous Integration workflow
# Runs tests, linting, and type checking on all PRs and main branch pushes
name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    name: Test, Lint, and Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    
    strategy:
      matrix:
        node-version: [20.x]
        # Can add more versions if needed: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run type checking
      run: npm run typecheck
    
    - name: Run tests
      run: npm test
      env:
        # Prevent tests from timing out in CI
        CI: true
    
    # Optional: Upload test coverage if you generate it
    # - name: Upload coverage reports
    #   uses: codecov/codecov-action@v3
    #   if: always()
  
  # E2E tests job - runs Playwright tests with optimized configuration
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Total job timeout - critical for performance
    permissions:
      contents: read
    
    strategy:
      fail-fast: false  # Continue other jobs if one fails
      matrix:
        shard: [1, 2, 3, 4]  # Split tests across 4 shards for parallel execution
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium  # Only install chromium for CI speed
    
    - name: Build Next.js application
      run: npm run build
      timeout-minutes: 5  # Build timeout
      env:
        # Required environment variables for build
        NEXTAUTH_URL: http://localhost:3000
        AUTH_TRUST_HOST: true
        NEXTAUTH_SECRET: test-secret-for-ci-only-minimum-32-characters-long
        DATABASE_SECRET_ARN: arn:aws:secretsmanager:us-east-1:123456789012:secret:test
        DATABASE_ARN: arn:aws:rds:us-east-1:123456789012:cluster:test
        AWS_REGION: us-east-1
        # Mock AI provider settings for build
        OPENAI_API_KEY: sk-test-mock-key-for-build-only
    
    - name: Start Next.js server
      run: |
        npm run start > server.log 2>&1 &
        SERVER_PID=$!
        echo "Server PID: $SERVER_PID"
        sleep 10
        # Check if server is running
        if ! curl -f http://localhost:3000 > /dev/null 2>&1; then
          echo "Server failed to start. Last 50 lines of server log:"
          tail -50 server.log || true
          echo "Continuing anyway for CI tests that don't require server..."
        else
          echo "Server started successfully"
        fi
      env:
        NEXTAUTH_URL: http://localhost:3000
        AUTH_TRUST_HOST: true
        NEXTAUTH_SECRET: test-secret-for-ci-only-minimum-32-characters-long
        DATABASE_SECRET_ARN: arn:aws:secretsmanager:us-east-1:123456789012:secret:test
        DATABASE_ARN: arn:aws:rds:us-east-1:123456789012:cluster:test
        AWS_REGION: us-east-1
        # Mock AI provider settings
        OPENAI_API_KEY: sk-test-mock-key-for-ci-only
        NODE_ENV: production
    
    - name: Run E2E tests
      run: npx playwright test --shard=${{ matrix.shard }}/${{ strategy.job-total }}
      timeout-minutes: 8  # Test execution timeout
      env:
        CI: true
        # Fix auth trust host issue
        NEXTAUTH_URL: http://localhost:3000
        AUTH_TRUST_HOST: true
        NEXTAUTH_SECRET: test-secret-for-ci-only-minimum-32-characters-long
        PLAYWRIGHT_BROWSERS_PATH: 0  # Use system-installed browsers
        # Mock database to prevent connection errors
        DATABASE_SECRET_ARN: arn:aws:secretsmanager:us-east-1:123456789012:secret:test
        DATABASE_ARN: arn:aws:rds:us-east-1:123456789012:cluster:test
        AWS_REGION: us-east-1
        # Disable real AWS calls in tests
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.shard }}
        path: playwright-report/
        retention-days: 7  # Reduced from 30 days to save storage
    
    - name: Upload test results JSON
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.shard }}
        path: test-results.json
        retention-days: 7
    
  # CDK validation job - checks infrastructure code
  cdk-validate:
    name: Validate CDK Infrastructure
    runs-on: ubuntu-latest
    timeout-minutes: 8
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Cache root dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: |
        npm ci
        cd infra && npm ci
    
    - name: Install CDK CLI
      run: npm install -g aws-cdk@2
    
    - name: Build CDK TypeScript
      run: cd infra && npm run build
    
    - name: Synthesize CDK stacks
      run: |
        cd infra
        cdk synth --all --no-lookups --context baseDomain=example.com
      env:
        # Dummy values for synthesis only - not for deployment
        CDK_DEFAULT_ACCOUNT: '123456789012'
        CDK_DEFAULT_REGION: 'us-east-1'
    
    # Show infrastructure changes on PRs
    - name: CDK Diff
      if: github.event_name == 'pull_request'
      run: |
        cd infra
        echo "## Infrastructure Changes" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        npx cdk diff --context baseDomain=example.com 2>&1 | tee -a $GITHUB_STEP_SUMMARY || true
        echo "```" >> $GITHUB_STEP_SUMMARY
      env:
        CDK_DEFAULT_ACCOUNT: '123456789012'
        CDK_DEFAULT_REGION: 'us-east-1'