# Continuous Integration workflow
# Runs tests, linting, and type checking on all PRs and main branch pushes
name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    name: Test, Lint, and Type Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    strategy:
      matrix:
        node-version: [20.x]
        # Can add more versions if needed: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run type checking
      run: npm run typecheck
    
    - name: Run tests
      run: npm test
      env:
        # Prevent tests from timing out in CI
        CI: true
    
    # Optional: Upload test coverage if you generate it
    # - name: Upload coverage reports
    #   uses: codecov/codecov-action@v3
    #   if: always()
  
  # E2E tests job - runs Playwright tests
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Build Next.js application
      run: npm run build
      env:
        # Required environment variables for build
        NEXTAUTH_URL: http://localhost:3000
        NEXTAUTH_SECRET: test-secret-for-ci-only
        DATABASE_SECRET_ARN: arn:aws:secretsmanager:us-east-1:123456789012:secret:test
        DATABASE_ARN: arn:aws:rds:us-east-1:123456789012:cluster:test
        AWS_REGION: us-east-1
    
    - name: Start Next.js server
      run: |
        npm run start &
        npx wait-on http://localhost:3000 --timeout 30000
      env:
        NEXTAUTH_URL: http://localhost:3000
        NEXTAUTH_SECRET: test-secret-for-ci-only
        DATABASE_SECRET_ARN: arn:aws:secretsmanager:us-east-1:123456789012:secret:test
        DATABASE_ARN: arn:aws:rds:us-east-1:123456789012:cluster:test
        AWS_REGION: us-east-1
    
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        CI: true
        # Mock authentication for CI
        NEXTAUTH_URL: http://localhost:3000
        NEXTAUTH_SECRET: test-secret-for-ci-only
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
  # CDK validation job - checks infrastructure code
  cdk-validate:
    name: Validate CDK Infrastructure
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Cache root dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: |
        npm ci
        cd infra && npm ci
    
    - name: Install CDK CLI
      run: npm install -g aws-cdk@2.209.0
    
    - name: Build CDK TypeScript
      run: cd infra && npm run build
    
    - name: Synthesize CDK stacks
      run: |
        cd infra
        cdk synth --context baseDomain=example.com
      env:
        # Dummy values for synthesis only - not for deployment
        CDK_DEFAULT_ACCOUNT: '123456789012'
        CDK_DEFAULT_REGION: 'us-east-1'
    
    # Show infrastructure changes on PRs
    - name: CDK Diff
      if: github.event_name == 'pull_request'
      run: |
        cd infra
        echo "## Infrastructure Changes" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        cdk diff --context baseDomain=example.com 2>&1 | tee -a $GITHUB_STEP_SUMMARY || true
        echo "```" >> $GITHUB_STEP_SUMMARY
      env:
        CDK_DEFAULT_ACCOUNT: '123456789012'
        CDK_DEFAULT_REGION: 'us-east-1'